version: '2.1'

services:
  db:
    container_name: upb-db
    restart: always
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend-app:
    container_name: upb-backend
    restart: on-failure
    build: .
    command:
      - /bin/sh
      - -c
      - |
        python project/manage.py makemigrations
        python project/manage.py migrate
        python project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
